# Generated by Django 2.2.12 on 2020-07-28 13:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('roshambo', '0002_auto_20200728_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hum_move',
            field=otree.db.models.IntegerField(choices=[[0, 'Камень'], [1, 'Бумага'], [2, 'Ножницы']], null=True, verbose_name='Ваш выбор:'),
        ),
    ]
