# Generated by Django 2.2.12 on 2020-07-28 12:58

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'my_survey_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'my_survey_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='Ваш возраст')),
                ('height', otree.db.models.IntegerField(null=True, verbose_name='Ваш рост в см')),
                ('gender', otree.db.models.StringField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10000, null=True, verbose_name='Ваш пол')),
                ('state', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Ваш факультет, 0 если неприменимо')),
                ('education', otree.db.models.StringField(choices=[('Начальное или неполное среднее', 'Начальное или неполное среднее'), ('Среднее (закончили школу)', 'Среднее (закончили школу)'), ('Среднее профессиональное (техникум, училище)', 'Среднее профессиональное (техникум, училище)'), ('Диплом бакалавра', 'Диплом бакалавра'), ('Диплом специалиста', 'Диплом специалиста'), ('Диплом магистра', 'Диплом магистра'), ('Аспирантура без получения учёной степени', 'Аспирантура без получения учёной степени'), ('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук')], max_length=10000, null=True, verbose_name='Ваш самый высокий уровень образования')),
                ('feedback_1', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Было ли что-то непонятным для Вас в эксперименте, если да, укажите что')),
                ('feedback_2', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Что по-вашему следует улучшить?')),
                ('feedback_3', otree.db.models.StringField(max_length=10000, null=True, verbose_name='О чем по вашему был этот эксперимент?')),
                ('feedback_4', otree.db.models.StringField(max_length=10000, null=True, verbose_name='чем вы руководствовались при выборе переменной и постоянной выплат (усилий), пользовались ли вы какой-либо стратегией?')),
                ('wage', otree.db.models.IntegerField(null=True, verbose_name='Ваш средний месячный доход, 0 если неприменимо')),
                ('experience', otree.db.models.StringField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10000, null=True, verbose_name='Принимали ли вы участие в экспериментах раньше?')),
                ('mark', otree.db.models.IntegerField(null=True, verbose_name='Балл за ЕГЭ по математике (укажите 0, если не помните)')),
                ('loneliness', otree.db.models.StringField(choices=[('Почти всегда', 'Почти всегда'), ('Часто', 'Часто'), ('Редко', 'Редко'), ('Почти никогда', 'Почти никогда')], max_length=10000, null=True, verbose_name='Вы испытываете чувство одиночества?')),
                ('trust', otree.db.models.StringField(choices=[('Большинству людей можно доверять', 'Большинству людей можно доверять'), ('С людьми всегда надо быть осторожным', 'С людьми всегда надо быть осторожным'), ('И то, и другое в зависимости от человека, условий', 'И то, и другое в зависимости от человека, условий')], max_length=10000, null=True, verbose_name='Считаете ли вы, что большинству людей можно доверять или что в отношениях с людьми всегда надо быть осторожным?')),
                ('max_satisf_min_1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Вне зависимости от того, насколько я доволен своей работой, мне кажется правильным искать лучшие возможности ')),
                ('max_satisf_min_2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Вне зависимости от того, что я делаю, я предъявляю к себе самые высокие требования ')),
                ('max_satisf_min_3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Я никогда не довольствуюсь чем-то второсортным ')),
                ('max_satisf_min_4', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Когда я выбираю из альтернатив, я останавливаюсь на первом варианте, который мне подходит ')),
                ('max_satisf_min_5', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' На работе или в учебе я всегда ставлю самые высокие цели ')),
                ('max_satisf_min_6', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' На работе или в учебе я склонен выбирать решения, которые гарантируют удовлетворяющие меня результаты ')),
                ('max_satisf_min_7', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' На работе или в учебе я ставлю цели, для достижения которых требуется минимальное усилие ')),
                ('max_satisf_min_8', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Всякий раз, когда я делаю выбор, я пытаюсь представить все альтернативы, даже те, которые отсутствуют в данный момент ')),
                ('max_satisf_min_9', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' На работе или в учебе я согласен с любым выбором, который приносит минимальный результат ')),
                ('max_satisf_min_10', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' В любой области я пытаюсь достичь удовлетворяющих меня результатов ')),
                ('max_satisf_min_11', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' На работе или в учебе даже минимальный результат может меня устроить ')),
                ('max_satisf_min_12', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' На работе или в учебе я трачу время на то, чтобы выбрать решение, которое меня устраивает ')),
                ('max_satisf_min_13', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Я всегда ставлю цели, для достижения которых требуется минимальное усилие ')),
                ('max_satisf_min_14', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Когда я принимаю решения, я трачу время на то, чтобы выбрать приемлемую для себя альтернативу ')),
                ('max_satisf_min_15', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Когда я должен принять решение, я выбираю вариант "по - минимуму" ')),
                ('max_satisf_min_16', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Когда передо мной встает новая задача, я трачу много времени на сбор информации о возможных путях ее решения ')),
                ('max_satisf_min_17', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' Когда на работе мне дают новое задание, я прилагаю не больше усилий, чем требуется ')),
                ('max_satisf_min_18', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' При выполнении рабочего задания я стремлюсь к максимальному результату, не считая потраченные силы и время ')),
                ('max_satisf_min_19', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' При выполнении любого задания я удовлетворяюсь результатом, который считаю достаточным на данный момент ')),
                ('max_satisf_min_20', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True, verbose_name=' При выполнения рабочего задания меня устроит результат, для достижения которого требуется минимум усилий ')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_survey.Subsession')),
            ],
            options={
                'db_table': 'my_survey_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_survey.Subsession'),
        ),
    ]
