# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-07 08:55
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='feedback_1',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Было ли что-то непонятным для Вас в эксперименте, если да, укажите что'),
        ),
        migrations.AddField(
            model_name='player',
            name='feedback_2',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Что по-вашему следует улучшить?'),
        ),
        migrations.AddField(
            model_name='player',
            name='feedback_3',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='О чем по вашему был этот эксперимент?'),
        ),
    ]
