# Generated by Django 2.2.12 on 2020-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realefforttask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='player',
            field=models.ForeignKey(on_delete='tasks', related_name='tasks', to='realefforttask.Player'),
        ),
    ]
