# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-07 08:55
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('guess_two_thirds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='best_guess',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='num_winners',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess',
            field=otree.db.models.PositiveIntegerField(null=True),
        ),
    ]
