# Generated by Django 2.2.12 on 2020-08-03 03:51

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_rps_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_rps_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_rps_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_rps_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('age', otree.db.models.PositiveIntegerField(null=True, verbose_name='Ваш возраст (полных лет)')),
                ('gender', otree.db.models.BooleanField(choices=[[0, 'Мужской'], [1, 'Женский']], null=True, verbose_name='Ваш пол')),
                ('height', otree.db.models.PositiveIntegerField(null=True, verbose_name='Ваш рост (в сантиметрах)')),
                ('guess', otree.db.models.PositiveIntegerField(null=True, verbose_name='загатайте целое число от 1 до 10')),
                ('city', otree.db.models.PositiveIntegerField(null=True, verbose_name='\n    Сколько человек (приблизительно) проживало в том населенном пункте, где Вы жили в возрасте 16 лет.')),
                ('math', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='как вы оцениваете свои знания в математике»)')),
                ('tigr', otree.db.models.BooleanField(choices=[[0, 'нет'], [1, 'да']], null=True, verbose_name='Проходили ли вы курс по теории игр')),
                ('equi', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Какие равновесия есть в игре "Камень-Ножницы-Бумага"? (впишите "не знаю" если не знаете как ответить на этот вопрос)')),
                ('trend0', otree.db.models.BooleanField(choices=[[0, 'нет'], [1, 'да']], null=True, verbose_name='как вам кажется подчинялся ли алгоритм оппонента конкретным правилам?')),
                ('trend2', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Как вы считаете, пользовался ли компьютер конкретным алгоритмом (да\\нет\\не знаю)? Если вы заметили какую-либо закономерность в работе программы, пожалуйста опишите её.')),
                ('univ', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Укажите ВУЗ, в котором Вы получили Ваше наивысшее образование.')),
                ('satis', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Учитывая все обстоятельства, насколько Вы удовлетворены вашей жизнью в целом в эти дни? (от 1 «полностью не удовлетворен» до 10 «полностью удовлетворен»)')),
                ('trust', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Как Вы считаете, в целом большинству людей можно доверять, или же при общении с другими людьми \n        осторожность никогда не повредит? Пожалуйста, отметьте позицию на шкале, где 1 означает "Нужно быть очень осторожным с другими людьми" и 10\n        означает "Большинству людей можно вполне доверять" ')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_rps.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_rps_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_rps_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_rps.Subsession')),
            ],
            options={
                'db_table': 'survey_rps_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_rps.Subsession'),
        ),
    ]
