# Generated by Django 2.2.12 on 2020-07-28 12:58

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('gtype', otree.db.models.StringField(max_length=10000, null=True)),
                ('realized_rounds_1', otree.db.models.FloatField(null=True)),
                ('realized_rounds_2', otree.db.models.FloatField(null=True)),
                ('total_return', otree.db.models.CurrencyField(null=True)),
                ('agent_last_risk_choice', otree.db.models.FloatField(null=True)),
                ('agent_average_risk_choice', otree.db.models.FloatField(null=True)),
                ('agent_fixed_pay', otree.db.models.CurrencyField(null=True)),
                ('agent_social_media_time_spend', otree.db.models.StringField(max_length=10000, null=True)),
                ('agent_numb_of_last_books', otree.db.models.StringField(max_length=10000, null=True)),
                ('agent_piece_rate', otree.db.models.FloatField(null=True)),
                ('expected_efforts', otree.db.models.FloatField(null=True)),
                ('Hum_effort', otree.db.models.FloatField(null=True)),
                ('viewed_risk_preff', otree.db.models.IntegerField(null=True)),
                ('viewed_social_media_time_spend', otree.db.models.IntegerField(null=True)),
                ('viewed_numb_of_last_books', otree.db.models.IntegerField(null=True)),
                ('total_return_Hum_A_vs_robot', otree.db.models.CurrencyField(null=True)),
                ('total_return_Hum_P_vs_robot', otree.db.models.CurrencyField(null=True)),
                ('robot_agent_offer_fixed_pay', otree.db.models.CurrencyField(null=True)),
                ('robot_agent_offer_piece_rate', otree.db.models.FloatField(null=True)),
                ('robot_effort', otree.db.models.FloatField(null=True)),
                ('eff_plus_eps', otree.db.models.FloatField(null=True)),
                ('eff_plus_eps_r', otree.db.models.FloatField(null=True)),
                ('swicher', otree.db.models.StringField(max_length=10000, null=True)),
                ('epsilon', otree.db.models.FloatField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_h_vs_r_group', to='otree.Session')),
            ],
            options={
                'db_table': 'contracts_H_vs_R_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_h_vs_r_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'contracts_H_vs_R_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('risk_coeff', otree.db.models.FloatField(null=True)),
                ('risk_choice', otree.db.models.FloatField(null=True)),
                ('numb_errors', otree.db.models.FloatField(null=True)),
                ('average_plrs_risk', otree.db.models.FloatField(null=True)),
                ('contract_game_payoff', otree.db.models.CurrencyField(null=True)),
                ('task_1', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Задание 1. Во одном из раундов Исполнитель выбрал уровень усилий 2.5  на шаге 2. На шаге 3 компьютер посчитал значение Случайного фактора, оно составило  2. Какова будет Выручка Заказчика?')),
                ('task_2', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Задание 2. Во втором этапе  Заказчик на шаге 1 в первом раунде предложил фиксированную часть вознаграждения  в размере 9, и переменную часть в размере 2.  Исполнитель предпринял уровень усилий 4 и компьютер на шаге 3 выбрал значение случайного фактора, оно составло - 1 (минус один). Сколько токентов получит Заказчик за раунд?')),
                ('task_4', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Сколько получит Исполнитель за один раунд? ')),
                ('task_5', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Задание 3. Исполнитель  на втором этапе в течение 20 раундов выигрывал в каждом раунде по 12 токенов, на первом этапе 17 токена. Сколько рублей в конце эксеримента получит участник в роле исполнителя? ')),
                ('task_6', otree.db.models.IntegerField(choices=[[1, '50%'], [2, '100%'], [3, 'прибизительно равна 95%'], [4, 'прибизительно равна 5% '], [5, 'прибизительно равна 1%']], null=True, verbose_name=' Задание 4. Выберите правильный ответ на вопрос:  Исполнитель в одном из раундов второго этапа, выбрал уровень усилий  в размере 6. Какова вероятность что результат усилий с учетом случайного фактора выйдет из интервала от 3 до 9 ?')),
                ('social_media_time_spend', otree.db.models.StringField(choices=[['0-4', '0-4'], ['5-9', '5-9'], ['10 и более', '10 и более']], max_length=10000, null=True, verbose_name='Укажите приблизительное количество стран, которое вы посетили?')),
                ('numb_of_last_books', otree.db.models.StringField(choices=[['0-2', '0-2'], ['3-5', '3-5'], ['6 и более', '6 и более']], max_length=10000, null=True, verbose_name='Укажите приблизительное количество книг, прочитанных вами за последние три месяца')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts_H_vs_R.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_h_vs_r_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_h_vs_r_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_H_vs_R.Subsession')),
            ],
            options={
                'db_table': 'contracts_H_vs_R_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_H_vs_R.Subsession'),
        ),
    ]
