# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-24 14:27
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_H_vs_R', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contract_accepted',
        ),
        migrations.RemoveField(
            model_name='group',
            name='robot_agent_fixed_pay',
        ),
        migrations.RemoveField(
            model_name='group',
            name='robot_agent_piece_rate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='type',
        ),
        migrations.AddField(
            model_name='group',
            name='agent_average_risk_choice',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='agent_last_risk_choice',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='agent_piece_rate',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='eff_plus_eps',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='eff_plus_eps_r',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='robot_agent_offer_fixed_pay',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='robot_agent_offer_piece_rate',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='swicher',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='numb_errors',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='risk_choice',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='risk_coeff',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='task_1',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Задание 1. Во втором этапе Участник 2 выбрал уровень усилий 2,5  на шаге 2. На шаге 3 компьютер посчитал значение удачи, оно составило  1,5. Каков будет общий заработок обоих участников?'),
        ),
        migrations.AddField(
            model_name='player',
            name='task_2',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Задание 2. Во втором этапе  Участник 1 на шаге 1 в первом раунде предложил фиксированную часть вознаграждения в размере 9, и переменную часть в размере 2.  Участник 2 предпринял усилия 4и компьютер на шаге 3 считал значение удачи, оно составло - 1. Какова вероятность того, что участник 1 получит 20 токенов за раунд?'),
        ),
        migrations.AddField(
            model_name='player',
            name='task_3',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Какова вероятность того, что участник 1 получит 0 токенов за раунд?'),
        ),
        migrations.AddField(
            model_name='player',
            name='task_4',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Сколько получит участник 2? '),
        ),
        migrations.AddField(
            model_name='player',
            name='task_5',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Задание 3. Участник 2  на втором этапе в течение 20 раундов выигрывал в каждом раунде по 12 токенов, на первом этапе 1, токена без учета поправочного коэфициента. Сколько рублей в конце эксеримента получит участник? (для использования 10-й записи используйте точку как разделитель)'),
        ),
        migrations.AddField(
            model_name='player',
            name='task_6',
            field=otree.db.models.IntegerField(choices=[[1, '50%'], [2, 'Приближается к 100%'], [3, '95%'], [4, 'Приближается к 1%'], [5, '5%']], null=True, verbose_name=' Задание 4. Выберите правильный ответ на вопрос:  Участник 2 в одном из раундов второго этапа, выбрал уровень усилий в размере 6. Какова вероятность что результат усилий с учетом удачи выйдет из интервала от 3 до 9 ?'),
        ),
    ]
