# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-11 19:59
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_H_vs_R', '0002_auto_20190724_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='expected_efforts',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='realized_rounds_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='realized_rounds_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='task_1',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Задание 1. Во втором этапе Участник 2 выбрал уровень усилий 2,5  на шаге 2. На шаге 3 компьютер посчитал значение Случайного фактора, оно составило  1,5. Каков будет общий заработок обоих участников?'),
        ),
    ]
